### ISSUE TITLE
Refresh function no longer working in Windows 10 2004

### ISSUE THREAD

**Issue by jay-99** [majkinetor/posh#10]
The refresh function no longer appears to be working after upgrading to Windows 10 2004 (it was working on 1909).  I've tested this on half a dozen computers and same result, so I believe something has changed in latest windows version which has caused this to stop working.  Any thoughts on how to resolve?

**Comment by majkinetor** [comment]
Not sure what you talking about ?

**Comment by jay-99** [comment]
Apologies.  This relates to Update-Proxy.ps1.  The script doesn't work in Windows 10 2004 and after some testing I believe it's to do with the 'refresh function' in the script no longer working.

**Comment by majkinetor** [comment]
It looks like it works for me the same as before (here in pwsh7):

![proxy](https://user-images.githubusercontent.com/85767/85689937-5cd46700-b6d3-11ea-8637-503c454a9545.gif)

**Comment by jay-99** [comment]
ok, thanks for checking.  I thought it was the new windows version but there must be some other policy on our system affecting this.  I will keep looking for the cause, will update you if I find anything of significance..

**Comment by majkinetor** [comment]
I also checked relevant MS docs about `INTERNET_OPTION_REFRESH` and `InternetSetOption` there isn't anything related to latest Windows version.

**Comment by jay-99** [comment]
Issue was actually not related to the internet set & refresh function which I ruled out after seeing it work properly in your video.  It was actually cause by the below highlighted line (in my code, not yours).  The offending line was actually stopping all registry changes being written on previous lines (which is why I thought it was the function).  For whatever reason, this worked in v1909 but stopped working in v2004.  Rather than trying to force remove the registry entry, I now perform a test to see if it exists and change the value to either 1 or 0.  I don't why why this behavior only affects this line and not the other lines that do the same thing, but can confirm now working.  Thanks for taking the time to reply.

$RegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
#Change Proxy in current users registry
Remove-ItemProperty -path $RegPath -Name AutoConfigURL -ErrorAction SilentlyContinue
Remove-ItemProperty -path $RegPath -Name ProxyServer -ErrorAction SilentlyContinue
Remove-ItemProperty -path $RegPath -Name ProxyOverride -ErrorAction SilentlyContinue
**Remove-ItemProperty -path $RegPath -Name ProxyEnable -ErrorAction SilentlyContinue**
